#!/usr/bin/env bash
#this displays bad luck for the 4th loop iteration\
#displays good luck for the 8th loop iteration\
#displays Best School for the other iterations

idx=1
while [ $idx -le 10 ]
do
	if [ $idx = 4 ]
	then
		echo "bad luck"
	elif [ $idx = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((idx++))
done
